### ISSUE TITLE
New-lines or cropping with three-dots functionality

### ISSUE THREAD

**Issue by somewonderfulguy** [effectussoftware/react-custom-roulette#116]
I understand that this is not an issue or bug. I'm creating this one because I need this and if this package will support it, that will be really great.
Two moment I'm going to point one. First, if user types very long text - it would be great to crop it with three dots, if such case is possible.
The other one I believe is more way more easier to implement is support of new-line character. Something to make it like: `Discount\n50%`.
Thanks.

**Comment by Acarvajal904** [comment]
Hi, thank you for your feedback, is not in out plan to include this feature, feel free to upload a MR and we can check it
