### ISSUE TITLE
I want use react native

### ISSUE THREAD

**Issue by mingyeom1** [effectussoftware/react-custom-roulette#12]
Hello, I want use react native.
But "ReferenceError: Can't find variable: Image" error
How to fix?

import React, {useState} from 'react';
import { Button, View, Image} from 'react-native';
import { Wheel } from 'react-custom-roulette

const ResultScreen = ({ navigation }: any) => {
    const [spin, setSpin] = useState(false)
    const data = [
        {option: '1'},
        {option: '2'},
        {option: '3'},
        {option: '4'},
        {option: '5'},
        {option: '6'},
]
    return (
        <View>
            <Wheel
                mustStartSpinning={spin}
                prizeNumber={1}
                data={data}
                backgroundColors={['#3e3e3e', '#df3428']}
                textColors={['#ffffff']} 
                />
            <Button title="spin" onPress={() => setSpin(true)} />
            <Button title="Go to Home" onPress={() => navigation.navigate('Home')} />
        </View>
    );
}

export default ResultScreen;

**Comment by Zercade** [comment]
Same error on iOS

**Comment by luchozamora1** [comment]
@mingyeom1 Thank you for the report! This library is compatible with React.js only, and at the moment we don't have a React Native version available.
