### ISSUE TITLE
image Prop vs options

### ISSUE THREAD

**Issue by ngtrthvu3007** [effectussoftware/react-custom-roulette#124]
why  the wheel only render images, do not render option string ?
my wheel before : 
![image](https://user-images.githubusercontent.com/103686648/233022174-f4adf414-3d90-476d-b955-0deed9c8a69f.png)
my wheel after:
![image](https://user-images.githubusercontent.com/103686648/233000358-5a7f701d-9f12-4afd-bb24-190969213f12.png)
 the options section are replaced by the image,
i try only the first option have image, and my wheel:
![image](https://user-images.githubusercontent.com/103686648/233044251-403827ab-a128-4d63-af43-755788b168bf.png)
note: i config imageProps like that: 
  uri: item.image,
   sizeMultiplier: 0.3,
    offsetX: 1,
    offsetY: 0.5,

**Comment by luchozamora1** [comment]
@ngtrthvu3007 Thank you for the feedback. Right now we set it up in a way that a wheel option can be either a text string or an image, but not both. Also, it is not in our plans to work on this feature, so feel free to create a PR with the necessary changes and we will make sure to check it.

**Comment by mclopez09** [comment]
How do you place the pointer in the middle?
