### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'NaN')

### ISSUE THREAD

**Issue by Arsenalist** [effectussoftware/react-custom-roulette#128]
Reproducible if you put the following in any component. Using NextJS 13 and latest version of react-custom-roulette. This works fine when mustSpin = false, but as soon as you set it to true the error happens

```
    const [mustSpin, setMustSpin] = useState(false)
    const data = [
        { option: '0', style: { backgroundColor: 'green', textColor: 'black' } },
        { option: '1', style: { backgroundColor: 'white' } },
        { option: '2' },
    ]
    return <div>
        <Wheel
            mustStartSpinning={mustSpin}
            prizeNumber={3}
            data={data}
            backgroundColors={['#3e3e3e', '#df3428', '#ffeeff']}
            textColors={['#ffffff']}
            onStopSpinning={() => {
                setMustSpin(false);
            }}
        />
        <button onClick={() => setMustSpin(true)}>Spin</button>
    </div>
```

**Comment by kanarian** [comment]
How did you fix this error @Arsenalist

**Comment by JihooDev** [comment]
@kanarian  Using the initial state value stored in "state" prevents this issue from occurring.
`
const [onSpin, setOnSpin] = useState(false);

...

    useEffect(() => {
        setOnSpin(true)
    }, [])

    return (
        <div className='event_container'>
            <div className='event_content_container'>
                <Wheel
                    mustStartSpinning={onSpin}
                    prizeNumber={2}
                    data={data}
                    backgroundColors={['#3e3e3e', '#df3428']}
                    textColors={['#ffffff']}
                />
            </div>
        </div>
    )



`

**Comment by berthelol** [comment]
Hey @Arsenalist @JihooDev this does not work for me.

Any tips ?

```
export const ChristmasWheel = () => {
  const [onSpin, setOnSpin] = useState(false)

  const onFinished = (winner: any) => {
    toast.success(`You won ${winner}`)
  }

  const handleSpin = () => {
    setOnSpin(true);
  }
  
  return <div>
    <Wheel
      mustStartSpinning={onSpin}
      prizeNumber={3}
      data={data}
      backgroundColors={['#3e3e3e', '#df3428']}
      textColors={['#ffffff']}
    />
    <Button onClick={handleSpin}>Launch</Button>
  </div>
}


```

**Comment by JihooDev** [comment]
> Hey @Arsenalist @JihooDev this does not work for me.
> 
> Any tips ?
> 
> ```
> export const ChristmasWheel = () => {
>   const [onSpin, setOnSpin] = useState(false)
> 
>   const onFinished = (winner: any) => {
>     toast.success(`You won ${winner}`)
>   }
> 
>   const handleSpin = () => {
>     setOnSpin(true);
>   }
>   
>   return <div>
>     <Wheel
>       mustStartSpinning={onSpin}
>       prizeNumber={3}
>       data={data}
>       backgroundColors={['#3e3e3e', '#df3428']}
>       textColors={['#ffffff']}
>     />
>     <Button onClick={handleSpin}>Launch</Button>
>   </div>
> }
> ```

where is your data ?

**Comment by alexvloure** [comment]
I also got this error. It's random, sometimes it happens when you spin the wheel 2 times, sometimes 5 times, sometimes 10... I have the mustStartSpinning prop in a state as @JihooDev suggested but that does not work.

```import { useState } from 'react';
import { Wheel as Roulette } from 'react-custom-roulette';

export default function Wheel() {
  const [isSpinning, setIsSpinning] = useState(false);
  const [prizeNumber, setPrizeNumber] = useState(null);
  const [data, setData] = useState([]);

  return (
    <>
      {data.length > 1 ? (
        <div className="rouletteContainer">
          <Wheel
            mustStartSpinning={isSpinning}
            prizeNumber={prizeNumber}
            data={data}
            onStopSpinning={resetWheel}
            backgroundColors={['#000']}
            textColors={['#ffffff']}
            outerBorderWidth={3}
            outerBorderColor={'#A28354'}
            innerRadius={22}
            radiusLineWidth={2}
            radiusLineColor={'#A28354'}
          />
          <button className="spinButton" onClick={() => handleSpin()}>
            SPIN
          </button>
          <div className="marker" />
        </div>
      ) : (
        <p>No data found. Please add at least 2 options.</p>
      )}
   </>
  );
}
```

**Comment by LuckyArdhika** [comment]
use prizeNumber={prizeNumber} // from state
