### ISSUE TITLE
run it only in js ? 

### ISSUE THREAD

**Issue by PhilDecreus** [effectussoftware/react-custom-roulette#15]
Hello i found the project is great but as a newbi i don't know how to use typescript ... is it possible to git clone this project and npm start it normally ?

any help ?

Regards,

**Comment by luchozamora1** [comment]
Hey @PhilDecreus, thanks for the question! The whole project was created and developed using the typescript template and file formats, as well as interfaces and types. So my opinion on the topic is that it will be way harder to revert to js than to keep it this way and try to work with the typescript features. Give it a shot and let me know if you have any further issues.
