### ISSUE TITLE
Window is not defined

### ISSUE THREAD

**Issue by Darrenwwk** [effectussoftware/react-custom-roulette#159]
Hi, I am using this package on my new nextjs project but getting this error 
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/darren/Desktop/food-spin/node_modules/.pnpm/react-custom-roulette@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/react-custom-roulette/dist/bundle.js:1:238).

I guess this is because this package is trying to access window in server side but not in client side. May I know how to handle this?

**Comment by Darrenwwk** [comment]
Problem is resolved after adding useEffect

**Comment by wedwin53** [comment]
Hi, how do you solved the issue? @Darrenwwk

**Comment by Darrenwwk** [comment]
> Hi, how do you solved the issue? @Darrenwwk

use `dynamic` from nextJs to import the package and close the server side rendering
