### ISSUE TITLE
Set defualt prizeNumber after first render wheel 

### ISSUE THREAD

**Issue by NikitaGura** [effectussoftware/react-custom-roulette#16]
Hello, thanks for good roulette. Have one question, is that posible after first render wheel set cursor on selected value wihtout spin?:)

**Comment by ekoydakoykoy** [comment]
also interested on how to set it u, i think so far the initial value is the last value from the data array.

**Comment by Acarvajal904** [comment]
Hi, thank you for your comments. Right now we are not planning on implementing this feature. Feel free to upload a PR and we can check it
