### ISSUE TITLE
Change the pointer color

### ISSUE THREAD

**Issue by fernandofantinel** [effectussoftware/react-custom-roulette#167]
How can I change the pointer color? 
I have tried the below props, but it didn't work.

```jsx
pointerProps={{
  style: {
    caretColor: "white",
  },
}}
```

**Comment by ghost** [comment]
pointerProps={{
              style: {
                filter: "contrast(0%) brightness(2)",
              },
            }}

**Comment by fernandofantinel** [comment]
Great!
I got it with `filter: "hue-rotate(26deg)"` function.
