### ISSUE TITLE
Do not stop the roulette until state changes

### ISSUE THREAD

**Issue by roy1210** [effectussoftware/react-custom-roulette#17]
Hi teams! I love this roulette, thank you for let me use it!
I notice this roulette will stop after 10 secs spin is started. Since my business logic takes quite a long time to has been chosen the prize number, is it possible to make roulette spinning (like forever) until `mustSpin` state becomes `false` ?

**Comment by roy1210** [comment]
Or maybe it is better to passing `spinTime` to `Wheel` component. Like `<Wheel spinTime={60000} />`  :D

**Comment by ayush-lal** [comment]
I am also interested in this. @roy1210 did you manage to figure out a work around?

**Comment by ekoydakoykoy** [comment]
i am waiting for this

**Comment by Gaston-Gonzalez** [comment]
This is now solved with `spinDuration` coefficient
