### ISSUE TITLE
Insert data with useState

### ISSUE THREAD

**Issue by nanderLP** [effectussoftware/react-custom-roulette#19]
Hey, I like your Component but I have a problem. I want to add/remove possible options from the Wheel with useState. I made a little [CodeSandbox](https://codesandbox.io/s/vigorous-beaver-7vpe9?file=/src/App.js) to show a example. For some reason the data in the Wheel is delayed by one State Update. You can see that by watching at the List with Options (Which is just the state, iterated as a jsx list). I don't know if this is a problem how I set/update the State or if the Component isn't compatible with it. I'd appreciate any kind of help 👋🏻

**Comment by luchozamora1** [comment]
Hey @nanderLP, thanks for reaching out! We just pushed a fix for this (#22). Could you update to `1.1.8` and check if it's working fine now?

**Comment by nanderLP** [comment]
Hey @luchozamora1, I just updated the CodeSandbox and it's working fine now. Thanks for the fix!
