### ISSUE TITLE
Roulette pointer image

### ISSUE THREAD

**Issue by KirillVasilev** [effectussoftware/react-custom-roulette#27]
It's a really cool thing. Thanks to the authors.
How can I change the roulette wheel picture?

![image](https://user-images.githubusercontent.com/84845134/119644339-6c998580-be25-11eb-8b95-a33e183125b4.png)

**Comment by Woverlin** [comment]
@KirillVasilev I had same issue and worked around,
you can try with this code
`img[alt~="roulette-static"] {
      position: absolute;
      z-index: 5;
      width: 10%;
      right: 35px;
      top: 35px;
      content: url("http://imgur.com/SZ8Cm.jpg");
    }`

**Comment by luchozamora1** [comment]
@Woverlin thank you for you solution, hope you were able to solve it using CSS.

In version **1.3.2** we've added a `pointerProps` prop to customize the wheel pointer with props instead.

```jsx
interface PointerProps {
  src?: string; // Optional
  style?: React.CSSProperties; // Optional
}
```

**Comment by unaldutlu** [comment]
Hi, I want to shape the outerBorder, how can I do it?  for example
![image](https://github.com/effectussoftware/react-custom-roulette/assets/94699375/91dd87e4-88aa-4e47-90f7-f838df6350d4)

**Comment by Syedfaizan3192** [comment]
pointerProps={{ src: CustomPointerImage }}
