### ISSUE TITLE
Idea: Inverse prize picker

### ISSUE THREAD

**Issue by eenlars** [effectussoftware/react-custom-roulette#3]
Cool project, I like it!

Is it possible to add an inverse prize picker? E.g. someone not winning the prize?

Thanks a ton!

**Comment by nazabalm20** [comment]
HI @eenlars , thanks for the feedback!
Can you expand your idea? We're thinking on adding a prop "winningPrizes", it would be an array of prizes with winning possibilities where the roulette select one randomly.

**Comment by eenlars** [comment]
Yes of course!

A prop like that could help a lot! Since sometimes, a previous choice of the user can influence whether an option would be possible to win.

For example, when you are making a drinking game, some of the options may already have been picked.

A possibility would be to have an array that's called data, a bit like this.


    let wheelInputs = [
    {
        'option': "Drink 2 beers",
        'picked': false
    }, 
    {
        'option': "Take a shot",
        'picked': false
    }, {
        'option': "Take 2 shots",
        'picked': true
    }] 

This way, the random picker sees which options are available to pick, using 

`
   const available = wheelInputs.filter((obj) => obj.picked).length
`

Then we can choose a random input using

`
    let pickIndex = Math.floor(Math.rand() * available)
`

    for(let i in wheelInputs) {
        if(pickIndex < 1 && !wheelInputs[i].picked) 
             return wheelInputs[i] .. maybe i to calculate angle
        else pickIndex = pickIndex - 1
    }



Eventually, it is possible to add even more keys for the objects.

**Comment by nazabalm20** [comment]
@eenlars  Thanks for the explanation! Now it is clear. 

To do this, first we need to implement the following:

- Possibility to spin the wheel again after a previous spin
- Add random picker that selects randomly from an array of options

After those two points are done, we can work on this feature! 

Thanks again for the suggestion

**Comment by and7ey** [comment]
@nazabalm20, did you manage to implement a possibility to spin the wheel again?

**Comment by luchozamora1** [comment]
The multi-spin functionality was added in https://github.com/effectussoftware/react-custom-roulette/pull/11
We'll keep adding features to the roulette, taking this suggestion into consideration. Thank you all
