### ISSUE TITLE
Modify option's radius size

### ISSUE THREAD

**Issue by dhatGuy** [effectussoftware/react-custom-roulette#30]
Is there a way to change the size of radius of an option, 
Let's say, the roulette wheel has two options. I want the first option radius to take 70% and the second 30%>

**Comment by luchozamora1** [comment]
@dhatGuy you can use the `optionSize` field from the `WheelData` interface. 

As stated in the documentation:
```
optionSize:

Integer that sets the size of the option measured in roulette pieces. 
For example: if data provides 2 options A and B, and you set A's optionSize to 2, 
B's optionSize to 1, the roulette will render 3 pieces: 2 corresponding to A and 
1 corresponding to B. Therefore, A will appear to be twice as big as B.
```
