### ISSUE TITLE
Problem with the hook call :(

### ISSUE THREAD

**Issue by HugoGDRM** [effectussoftware/react-custom-roulette#32]
When i try to launch your example i got this error
`Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.`

**Comment by HugoGDRM** [comment]
I search for many solutions but nothing is working, thanks for your help

**Comment by luchozamora1** [comment]
Added some documentation on how to run the example app. You can check it [here](https://github.com/effectussoftware/react-custom-roulette/tree/master/example#running-the-example).

Let me know if it fixes the issues, closing for now.
