### ISSUE TITLE
reference Error: window is not defined

### ISSUE THREAD

**Issue by PMainali6** [effectussoftware/react-custom-roulette#4]
The library is throwing reference error in the load itself for react project. 
![spinwheel-error](https://user-images.githubusercontent.com/10397682/86216666-074cfe00-bb9c-11ea-8e96-b750787fed6b.png)

**Comment by luchozamora1** [comment]
@PMainali6 Thanks for your report!

We weren't able to replicate this error, could you tell us which version of node and react are you using?

**Comment by ekoydakoykoy** [comment]
i think this issue happens when you use Next.js as it is has pre-rendering capabilities. you need to do Dynamic render. i fix this using below as instead of importing the library right away.

`import dynamic from "next/dynamic";

const Wheel = dynamic(
  () => {
    return import("react-custom-roulette").then((mod) => mod.Wheel);
  },
  { ssr: false }
);`

**Comment by SimonBowers** [comment]
Thanks, that worked for me when using Next.js
