### ISSUE TITLE
Ability to change spin duration

### ISSUE THREAD

**Issue by samhoogantink** [effectussoftware/react-custom-roulette#44]
Is it possible to add a custom spin duration? Will be really helpful.

**Comment by IvanAdmaers** [comment]
Unfortunately this package doesn’t yet support a custom spin duration.

**Comment by samhoogantink** [comment]
@maintainers, is it possible to accept this pull request? #40

**Comment by IvanAdmaers** [comment]
I think this package doesn't longer maintain by its owners. You can take a look on my [react roulette](https://github.com/IvanAdmaers/react-roulette-pro) that supports a custom spinning time.

**Comment by luchozamora1** [comment]
Now thanks to @TakeshiOnishi , version `1.2.0` of this library supports a `spinDuration` prop to adjust the spinning animation time! 🎉
