### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by santoshi15** [effectussoftware/react-custom-roulette#57]
I'm attempting to implement this in my NextJS React app via Typescript, but continue to get an error 'ReferenceError: window is not defined'

**Comment by bsmith20681** [comment]
I'm getting the same issue, did you ever find a solution?

**Comment by antrtr** [comment]
I get the same issue with Next.js too.

**Comment by Amphaal** [comment]
With Next.js, you can use some kind of a workaround by disabling SSR explicitly https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr

```
const Wheel = dynamic(
    () => import('react-custom-roulette').then(mod => mod.Wheel),
    { ssr: false }
)
```

... yet, Typescript still complains even if it compiles, so it is not perfect :'(

**Comment by Acarvajal904** [comment]
Hi, thank you for your comments. We are aware of the webpack problem, right now we can suggest to use the @Amphaal workaround.
