### ISSUE TITLE
Works only once problem

### ISSUE THREAD

**Issue by ahmetcanaydemir** [effectussoftware/react-custom-roulette#6]
Spin animation works only when changing **mustStartSpinning** prop first time, otherwise roulette directly showing the result without animation. If I manually remove the **.started-spinning** class from DOM and start again it works fine. I didn't try but maybe these changes fix the problem.

```javascript
const startSpinning = () => {
    setHasStartedSpinning(true);
    setHasStoppedSpinning(false) // +
    setTimeout(() => {
      setHasStartedSpinning(false); // +
      setHasStoppedSpinning(true);
    }, START_SPINNING_TIME + CONTINUE_SPINNING_TIME + STOP_SPINNING_TIME - 300);
  };
```

![0yfvaHPMir](https://user-images.githubusercontent.com/8572957/89120778-9615a900-d4c1-11ea-9cf1-943304e14c30.gif)

**Comment by josefdclxvi** [comment]
i have the same problem. in the initial spin, the animation works fine, but when i spin again the wheel the animation isnt working properly

**Comment by and7ey** [comment]
I am looking for solution also.

**Comment by and7ey** [comment]
@ahmetcanaydemir have you found the solution?

**Comment by xi1570-krupeshanadkat** [comment]
Also looking for solution, I thing we need to render the whole component again on ever button click

**Comment by luchozamora1** [comment]
@ahmetcanaydemir Hey! Just pushed a multi-spin feature, you can find a basic example here: 
https://github.com/effectussoftware/react-custom-roulette#multi-spin

Could you try it out and tell me if it's working as expected?

**Comment by and7ey** [comment]
I don't think it works - see https://wheel.wss.repl.co/ (https://repl.it/@wss/Wheel#src/App.js)

Btw, is there any way to control wheel speed? (or calculate time when it will finish spinning?)

**Comment by luchozamora1** [comment]
@and7ey Can you show exactly how are you calling the Wheel component? If you see in the example, you would have to add something like this for it to work:

```
onStopSpinning={() => {
     setMustSpin(false)
}}
```

In the /example folder there's a working example of this feature.

Also, no. At the moment there's only one spin speed, we will discuss it and see if we can add this feature on a future release!

**Comment by and7ey** [comment]
You may see the code at the second link I gave - https://repl.it/@wss/Wheel#src/App.js
I just copied your example.

**Comment by luchozamora1** [comment]
@and7ey Just saw you had version 1.1.4 in your package.json. Try upgrading to 1.1.5 and it should work

**Comment by and7ey** [comment]
Thanks, it works well now.
Sorry for the confusion - I was checking the packages tab at repl.it and it was showing the latest version 1.1.5.
