### ISSUE TITLE
Multiple instances of Wheel flikker when spinning stops

### ISSUE THREAD

**Issue by saltslag** [effectussoftware/react-custom-roulette#64]
When using multiple instances of a Wheel component with MiltiSpin, the last wheels seem to 'flikker' to the richt index after they stopped spinning

**Comment by sonykashyap** [comment]
Having the same issue on multiple instances of wheel.
Did not find any solution even after tried variety of different ways.

**Comment by luchozamora1** [comment]
This should have been fixed in version **1.3.2** ! Thank you for your feedback
