### ISSUE TITLE
ERROR  ReferenceError: Can't find variable: Image

### ISSUE THREAD

**Issue by RodrigoIbarraSanchez** [effectussoftware/react-custom-roulette#76]
I'm trying to implement in React Native but several errors occur when I installed the dependency.
For example:  ERROR  Error: Requiring module "node_modules/react-custom-roulette/dist/bundle.js", which threw an exception: ReferenceError: Can't find variable: Image 

Another issues are:
 ERROR  TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[4], "react-custom-roulette").Wheel')

This error is located at:
    in App (at renderApplication.js:50)
    in RCTView (at View.js:32)
    in Unknown (at AppContainer.js:92)
    in RCTView (at View.js:32)
    in Unknown (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:43)
    in WinRoyTSProject(RootComponent) (at renderApplication.js:60)
 ERROR  TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[4], "react-custom-roulette").Wheel')

This error is located at:
    in App (at renderApplication.js:50)
    in RCTView (at View.js:32)
    in Unknown (at AppContainer.js:92)
    in RCTView (at View.js:32)
    in Unknown (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:43)
    in WinRoyTSProject(RootComponent) (at renderApplication.js:60)

It's related because is a React Native App and not a React project?

**Comment by luchozamora3** [comment]
@RodrigoIbarraSanchez Correct. The library was made for React projects only!

**Comment by luchozamora1** [comment]
@RodrigoIbarraSanchez Correct. The library was made for React projects only!
