### ISSUE TITLE
Feature : To Support Multi Line Text in side wheel 

### ISSUE THREAD

**Issue by Sowmya-Appscrip** [effectussoftware/react-custom-roulette#77]
Hi, I am Sowmya, I would like to thank you guys for this wonderful custom module for roulette feature. But I need one more feature to add, that is,  inside spin wheel  to show multi line texts if in case it is possible I am sharing the image as well for reference . 
![image](https://user-images.githubusercontent.com/86068492/168776549-40a47570-d5bf-45d2-8759-b3de0a3c3ad0.png) with central allignment. Thank you in advance.

**Comment by sonykashyap** [comment]
Hi @Sowmya-Appscrip ,
Is your problem solved?
I am also seeking this feature and thought to ask you first if this feature is available.

**Comment by Acarvajal904** [comment]
Hi @Sowmya-Appscrip right now are not planning on implement this feature, feel free to upload a PR and we can check it
