### ISSUE TITLE
What is the way to add image in option?

### ISSUE THREAD

**Issue by sonykashyap** [effectussoftware/react-custom-roulette#89]
![image](https://user-images.githubusercontent.com/58991617/180970703-05358b32-1ca8-41f5-b7de-58073be1a77b.png)

**Comment by IvanAdmaers** [comment]
By using [react-roulette-pro](https://github.com/IvanAdmaers/react-roulette-pro) you can easily set images for your items.

**Comment by sonykashyap** [comment]
Hi @IvanAdmaers ,
Thanks! for suggesting react-roulette-pro.
Is it possible to change to a wheel shape instead of a horizontal and vertical one?

**Comment by IvanAdmaers** [comment]
Hi, @sonykashyap. Unfortunately it's not possible at this moment.

> Hi @IvanAdmaers , Thanks! for suggesting react-roulette-pro. Is it possible to change to a wheel shape instead of a horizontal and vertical one?

**Comment by luchozamora1** [comment]
@sonykashyap Thanks for your question! In version **1.3.2** we've added an `image: ImageProps` option in the WheelData interface (for each item of the `data` prop array). These are the available customization options:

```jsx
interface ImageProps {
  uri: string;
  offsetX?: number; // Optional
  offsetY?: number; // Optional
  sizeMultiplier?: number; // Optional
  landscape?: boolean; // Optional
}
```
The documentation is also updated. 

Let me know if you have any questions about it, or if you find any issues/improvements. Thank you!
