### ISSUE TITLE
Is there anyway to fully customize?

### ISSUE THREAD

**Issue by Kmak1234** [effectussoftware/react-custom-roulette#91]
Is there any possibily to fully edit and customize the roulette?
For example, can I remove the red arrow and add a different arrow

**Comment by IvanAdmaers** [comment]
If you need a customizable roulette you may take a look on [react-roulette-pro](https://github.com/IvanAdmaers/react-roulette-pro). There is an answer in the [FAQ](https://github.com/IvanAdmaers/react-roulette-pro#faq) section that describes how to customize it. And by the way it supports plugins.

**Comment by TimNZ** [comment]
@IvanAdmaers Curious how you ended up calling it Roulette which is well understood to be a wheel.

**Comment by estoylive** [comment]
is this IvanAdmaers everywhere in here posting his "roulette"? dude... come on. ANNOYING

**Comment by IvanAdmaers** [comment]
Hi, @estoylive. I'm sorry for be annoying with my [react-roulette-pro](https://github.com/IvanAdmaers/react-roulette-pro). But you should keep it in mind that there is a freedom of speech which means I can tell you about the cool roulette called [react-roulette-pro](https://github.com/IvanAdmaers/react-roulette-pro). Thank you for understanding it and always remember about [react-roulette-pro](https://github.com/IvanAdmaers/react-roulette-pro). Feel free to get in touch with me about [react-roulette-pro](https://github.com/IvanAdmaers/react-roulette-pro). It's ok to love this roulette called [react-roulette-pro](https://github.com/IvanAdmaers/react-roulette-pro). Be yourself. Thank you, dear. Link - [react-roulette-pro](https://github.com/IvanAdmaers/react-roulette-pro)

**Comment by estoylive** [comment]
this is not free speech is SPAM SPEECH xD I don't understand how people from this repository didn't even banned you

**Comment by IvanAdmaers** [comment]
Listen to me brother. You have better to stop bully my best RRP. Because this is the ninth wonder of the world you know. Otherwise let's meet in Ohio and discuss it face to face you know. Hope you understand man. I'm waiting for an apology video from you where you must say you love my RRP you know. I'm not joking dude. Don't be afraid and meet me in Ohio. I hope you're a good man and I won't need to meet you in Mexico you know. Thanks for understanding man. I'm waiting for that vidOn 27 Feb 2023, at 9:40 a.m., estoylive ***@***.***> wrote:﻿
this is not free speech is SPAM SPEECH xD I don't understand how people from this repository didn't even banned you

**Comment by franraknic** [comment]
Seeing that there is a lively discussion here, ill just ask here...

Has anyone succeded in adding an image to the data prop array?

this does not work, the images don't even get requested:  
```
const data = [
        { option: '0', image: { uri: "https://picsum.photos/200/200?random=1"}},
        { option: '1', image: { uri: "https://picsum.photos/200/200?random=2"}},
      ]
```

In all the examples there is no image prop added to the options array.

Thank you for the component!

**Comment by luchozamora1** [comment]
Thanks for all the comments and for keepping it peaceful..

In version **1.3.2** we've added a couple props to improve the wheel's customization, such as font family, font size, images as items, the pointer image, etc. All those changes are updated in the documentation.

@franraknic we've re-published the package so those changes should be working now. Let me know!
