### ISSUE TITLE
Is there any way to change the position of red pin point image?

### ISSUE THREAD

**Issue by UmeshKrRana** [effectussoftware/react-custom-roulette#94]
Hi, first of all, thank you very much for this wonderful library.
I have a concern, can we change the position of the red pinpoint image, I want it to be on top **(0 degree)** instead of right **(45 degree)**.
Is it possible to customize it by changing its position?
Using CSS we cannot do that because the winning result index is taking that same position.
Please help me with this.
Thank you.

**Comment by UmeshKrRana** [comment]
Hi @sonykashyap 
Thank you for your response. Can you please brief it more on how you did that?

**Comment by sonykashyap** [comment]
Hi @UmeshKrRana 
What I did I rotated the canvas by the number of degrees toward my required direction. 
Suppose you need a pin at the center toward the right side. So rotate it by 36deg.
Here is the CSS. The hmoclu is the canvas class. You might have some other class.
.hmocIu{
transform: rotate(36deg);
}

**Comment by UmeshKrRana** [comment]
Hi @sonykashyap 
Thank you for your valuable response. It worked :)

**Comment by Kolajosh** [comment]
Hi @sonykashyap how do i put the pin at the center of the wheel on both axis with the pointer pointing upwards?
