### ISSUE TITLE
Installing this package adds 200MB to node_modules

### ISSUE THREAD

**Issue by danieleff** [effectussoftware/react-custom-roulette#96]
Simply executing:

`npm install --save react-custom-roulette`

says "added 1893 packages, and audited 1894 packages in 1m", and creates a node_modules folder of 200MB.

Please move `react-scripts` from `dependencies` to `devDependencies` in package.json.

(Actually all of the dependencies can be moved to devdependencies, as nothing is needed to use this package.)

**Comment by luchozamora1** [comment]
@danieleff Thank you for the feedback. This has been fixed in version 1.3.2
